// Generated by CoffeeScript 1.6.3
/*
A basic jaadi plugin
*/

var Jaadi, JaadiPlugin,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

JaadiPlugin = (function() {
  function JaadiPlugin(storage) {
    this.storage = storage != null ? storage : {};
  }

  JaadiPlugin.prototype.get = function(key) {};

  JaadiPlugin.prototype.put = function(key, value) {};

  JaadiPlugin.prototype.remove = function(key) {};

  JaadiPlugin.prototype.size = function() {};

  JaadiPlugin.prototype.clear = function() {};

  JaadiPlugin.prototype.items = function() {
    var key, val, _items, _ref;
    _items = [];
    _ref = this._storage;
    for (key in _ref) {
      val = _ref[key];
      _items.push([key, val]);
    }
    return _items;
  };

  JaadiPlugin.prototype.parseJSON = function(item) {
    try {
      return JSON.parse(item);
    } catch (_error) {
      return null;
    }
  };

  return JaadiPlugin;

})();

Jaadi = (function() {
  /*
      default javascript DOM storage implementation
  */

  var DomStoragePlugin,
    _this = this;

  function Jaadi() {}

  DomStoragePlugin = (function(_super) {
    __extends(DomStoragePlugin, _super);

    function DomStoragePlugin() {
      this._container = {};
    }

    DomStoragePlugin.prototype.get = function(key) {
      return this._container[key];
    };

    DomStoragePlugin.prototype.put = function(key, value) {
      return this._container[key] = value;
    };

    DomStoragePlugin.prototype.remove = function(key) {
      return delete this._container[key];
    };

    DomStoragePlugin.prototype.size = function() {
      var key, length, val, _ref;
      length = 0;
      console.log(this._container);
      _ref = this._container;
      for (key in _ref) {
        val = _ref[key];
        length++;
      }
      return length;
    };

    DomStoragePlugin.prototype.items = function() {
      var key, val, _items, _ref;
      _items = [];
      _ref = this._container;
      for (key in _ref) {
        val = _ref[key];
        _items.push([key, val]);
      }
      return _items;
    };

    return DomStoragePlugin;

  })(JaadiPlugin);

  Jaadi.createInstance = function(name) {
    var jaadiType;
    try {
      jaadiType = Jaadi.plugins.get(name);
      if ('__super__' in jaadiType) {
        jaadiType = new jaadiType;
      } else if (typeof jaadiType === "function") {
        jaadiType = jaadiType.call();
      }
    } catch (_error) {
      throw "Implementation " + name + " not available";
    }
    return jaadiType;
  };

  Jaadi.plugins = new DomStoragePlugin();

  Jaadi.plugins.add = function(key, value) {
    return this.put(key, value);
  };

  Jaadi.plugins.add("dom", DomStoragePlugin);

  return Jaadi;

}).call(this);
